### ISSUE TITLE
Segmentation Fault on Python3.8 using vanilla OpenCV layer

### ISSUE THREAD

**Issue by oliverhowden** [iandow/opencv_aws_lambda#5]
Thanks heaps for the scripts, really useful. 
Using a vanilla python 3.8 runtime with just the layer, there is a segmentation fault due to a missing `libgthread-2.0.so.0`. If this lib is provided in the deployment zip, there is a segfault still, though there is no stacktrace.

```/task/<frozen importlib._bootstrap>\", \"pre_context\": [], \"context_line\": \"\", \"post_context\": []}, {\"filename\": \"<frozen importlib._bootstrap>\", \"lineno\": 1014, \"function\": \"_gcd_import\", \"library_frame\": false, \"abs_path\": \"/var/task/<frozen importlib._bootstrap>\", \"pre_context\": [], \"context_line\": \"\", \"post_context\": []}, {\"filename\": \"/var/lang/lib/python3.8/importlib/__init__.py\", \"lineno\": 127, \"function\": \"import_module\", \"library_frame\": false, \"abs_path\": \"/var/lang/lib/python3.8/importlib/__init__.py\", \"pre_context\": [], \"context_line\": \"return _bootstrap._gcd_import(name[level:], package, level)\", \"post_context\": []}, {\"filename\": \"/var/task/serverless_sdk/__init__.py\", \"lineno\": 54, \"function\": \"get_user_handler\", \"library_frame\": false, \"abs_path\": \"/var/task/serverless_sdk/__init__.py\", \"pre_context\": [], \"context_line\": \"user_module = import_module(user_module_name)\", \"post_context\": []}, {\"filename\": \"/var/task/s_process_image.py\", \"lineno\": 18, \"function\": \"<module>\", \"library_frame\": false, \"abs_path\": \"/var/task/s_process_image.py\", \"pre_context\": [], \"context_line\": \"user_handler = serverless_sdk.get_user_handler('handler.process_image')\", \"post_context\": []}, {\"filename\": \"/var/task/s_process_image.py\", \"lineno\": 23, \"function\": \"error_handler\", \"library_frame\": false, \"abs_path\": \"/var/task/s_process_image.py\", \"pre_context\": [], \"context_line\": \"raise e\", \"post_context\": []}, {\"filename\": \"/var/task/serverless_sdk/__init__.py\", \"lineno\": 130, \"function\": \"wrapped_handler\", \"library_frame\": false, \"abs_path\": \"/var/task/serverless_sdk/__init__.py\", \"pre_context\": [], \"context_line\": \"return user_handler(event, context)\", \"post_context\": []}, {\"filename\": \"/var/task/serverless_sdk/__init__.py\", \"lineno\": 401, \"function\": \"transaction\", \"library_frame\": false, \"abs_path\": \"/var/task/serverless_sdk/__init__.py\", \"pre_context\": [], \"context_line\": \"yield\", \"post_context\": []}]", "errorExceptionType": "ImportError", "errorId": "ImportError!$libgthread-2.0.so.0: cannot open shared object file: No such file or directory", "errorFatal": true}}, "requestId": "75deb0d2-193a-4813-8757-ec583809ca12", "schemaVersion": "0.0", "timestamp": "2020-04-28T07:55:51.477661Z"}
[ERROR] ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 130, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/s_process_image.py", line 23, in error_handler
    raise e
  File "/var/task/s_process_image.py", line 18, in <module>
    user_handler = serverless_sdk.get_user_handler('handler.process_image')
  File "/var/task/serverless_sdk/__init__.py", line 54, in get_user_handler
    user_module = import_module(user_module_name)
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/handler.py", line 3, in <module>
    import cv2
  File "/opt/python/lib/python3.8/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *END RequestId: 75deb0d2-193a-4813-8757-ec583809ca12
REPORT RequestId: 75deb0d2-193a-4813-8757-ec583809ca12	Duration: 86.91 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 84 MB	Init Duration: 271.57 ms	
RequestId: 75deb0d2-193a-4813-8757-ec583809ca12 Error: Runtime exited with error: signal: segmentation fault (core dumped)
Runtime.ExitError
```

Any chance you have any ideas? I've been scratching my head at this all day!

**Comment by josephjohansson** [comment]
Facing the same issue with the same setup

**Comment by josephjohansson** [comment]
Found a fix to this. This is based on this reply https://stackoverflow.com/questions/61924316/serverless-issue-with-aws-lambda-and-open-cv-in-python
Below is the edited Dockerfile
`FROM amazonlinux

WORKDIR /

# Install Python 3.8
RUN yum install gcc openssl-devel bzip2-devel libffi-devel wget tar gzip make zip libXext libSM libXrender -y
RUN wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
RUN tar -xzvf Python-3.8.0.tgz
WORKDIR /Python-3.8.0
RUN ./configure --enable-optimizations
RUN make install

# Install Python packages
RUN mkdir /packages
RUN echo "opencv-python" >> /packages/requirements.txt
RUN mkdir -p /packages/opencv-python-3.8/python/lib/python3.8/site-packages
RUN pip3.8 install -r /packages/requirements.txt -t /packages/opencv-python-3.8/python/lib/python3.8/site-packages


# Create zip files for Lambda Layer deployment
WORKDIR /packages/opencv-python-3.8/
RUN mkdir -p lib
RUN cp /lib64/libgthread-2.0.so.0 lib/
RUN cp /lib64/libglib-2.0.so.0 lib/
RUN cp /lib64/libSM.so.6 lib/
RUN cp /lib64/libICE.so.6 lib/
RUN cp /lib64/libXrender.so.1 lib/
RUN cp /lib64/libXext.so.6 lib/
RUN cp /lib64/libX11.so.6 lib/
RUN cp /lib64/libuuid.so.1 lib/
RUN cp /lib64/libxcb.so.1 lib/
RUN cp /lib64/libXau.so.6 lib/
RUN zip -r9 /packages/cv2-python38.zip .
WORKDIR /packages/
RUN rm -rf /packages/opencv-python-3.8/`
